import { useState } from 'react';
import { ethers, type Eip1193Provider } from 'ethers';
// Make sure this path is correct for your project
import LandRegistryABI from './artifacts/LandRegistry.json';

/**
 * Defines the structure of the JSON file generated by Truffle/Hardhat
 */
interface NetworkData {
  address: string;
}

interface LandRegistryArtifact {
  abi: ethers.Interface | ethers.InterfaceAbi;
  networks: Record<string, NetworkData | undefined>;
}

/**
 * Cast the imported JSON to our strict interface
 */
const ContractData = LandRegistryABI as unknown as LandRegistryArtifact;

/**
 * Define the MetaMask provider on the window object without using 'any'
 */
declare global {
  interface Window {
    ethereum?: Eip1193Provider & {
      send: (method: string, params: unknown[]) => Promise<unknown>;
    };
  }
}

export const useBlockchain = () => {
  const [account, setAccount] = useState<string | null>(null);

  /**
   * Connects to MetaMask and saves the wallet address
   */
  const connectWallet = async (): Promise<string | null> => {
    if (!window.ethereum) {
      alert("Please install MetaMask to use this feature.");
      return null;
    }
    
    try {
      const provider = new ethers.BrowserProvider(window.ethereum);
      // Ask user to share their wallet address
      const accounts = await provider.send("eth_requestAccounts", []) as string[];
      const connectedAccount = accounts[0] || null;
      
      setAccount(connectedAccount);
      return connectedAccount;
    } catch (error) {
      console.error("User did not allow access:", error);
      return null;
    }
  };

  /**
   * Gets the smart contract instance for making transactions
   */
  const getContract = async (): Promise<ethers.Contract> => {
    if (!window.ethereum) {
      throw new Error("MetaMask is required.");
    }

    const provider = new ethers.BrowserProvider(window.ethereum);
    const signer = await provider.getSigner();
    
    const network = await provider.getNetwork();
    const chainId = network.chainId.toString();

    // Check the JSON for a deployment on the current network
    let contractAddress = ContractData.networks[chainId]?.address;

    // Fallback: If not on the current network, check if there's any deployment in the JSON
    if (!contractAddress) {
      const networkIds = Object.keys(ContractData.networks);
      if (networkIds.length > 0) {
        contractAddress = ContractData.networks[networkIds[0]]?.address;
        console.warn("Using the first contract address found in build files.");
      }
    }

    if (!contractAddress) {
      throw new Error("Could not find the contract address. Please check your deployment.");
    }

    return new ethers.Contract(
      contractAddress, 
      ContractData.abi, 
      signer
    );
  };

  return { connectWallet, getContract, account };
};